version: "3.7"

services:

  facs-csconsts:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-csconsts:__FAC_CSCONSTS_TAG_TEMPLATE__
    deploy:
      placement:
        constraints:
          - node.hostname == IA-16RaBbB-CO-IOCSrv
      replicas: 1
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - host_network

networks:
  host_network:
    external:
      name: "host"
