version: "3.7"
services:

  fac-csconsts:
    image: dockerregistry.lnls-sirius.com.br/fac/fac-csconsts:${DEPLOY_TAG}
    build:
      context: "."
      dockerfile: "Dockerfile.csconsts"
      args:
        - BASE_IMAGE_TAG=${FAC_IMG_HTTPD_TAG}
        - REP_CSCONSTS_VERSION=${REP_CSCONSTS_VERSION}
      labels:
        - "br.com.lnls-sirius.department=FAC"
    ports:
      - "20080:20080"
